on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose environment
        required: true
        default: staging
        type: choice
        options:
          - staging 
          - production
          
          


jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print_msg
        run: echo "running the manual workflow..."
